CREATE TABLE "pg-drizzle_ai_preferences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_ai_preferences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"companyKnowledge" text,
	"toneOfVoice" text,
	"exampleMessages" text,
	"onboardingCompleted" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_ai_preferences" ADD CONSTRAINT "pg-drizzle_ai_preferences_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ai_preferences_user_idx" ON "pg-drizzle_ai_preferences" USING btree ("userId");