CREATE TABLE "pg-drizzle_company" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"linkedinProviderId" varchar(100),
	"linkedinUrl" varchar(500),
	"industry" varchar(150),
	"size" varchar(50),
	"website" varchar(500),
	"ownerId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_contact" ADD COLUMN "linkedinProviderId" varchar(100);--> statement-breakpoint
ALTER TABLE "pg-drizzle_contact" ADD COLUMN "linkedinUrl" varchar(500);--> statement-breakpoint
ALTER TABLE "pg-drizzle_contact" ADD COLUMN "companyId" integer;--> statement-breakpoint
ALTER TABLE "pg-drizzle_company" ADD CONSTRAINT "pg-drizzle_company_ownerId_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "company_owner_idx" ON "pg-drizzle_company" USING btree ("ownerId");--> statement-breakpoint
CREATE UNIQUE INDEX "company_linkedin_provider_owner_idx" ON "pg-drizzle_company" USING btree ("linkedinProviderId","ownerId");--> statement-breakpoint
ALTER TABLE "pg-drizzle_contact" ADD CONSTRAINT "pg-drizzle_contact_companyId_pg-drizzle_company_id_fk" FOREIGN KEY ("companyId") REFERENCES "public"."pg-drizzle_company"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "contact_linkedin_provider_owner_idx" ON "pg-drizzle_contact" USING btree ("linkedinProviderId","ownerId");